### ISSUE TITLE
AllCast Receiver (chrome app) full screen handling issue & fix.

### ISSUE THREAD

**Issue by cirdog** [koush/support-wiki#29]
Hi,

I've been fiddling around with Mirror + AllCast Receiver (chrome app) and found out that the captured video doesn't scale-fit after going full screen.

Please kindly add back **.player canvas** into window.css to make it scale correctly.

```css
.player video, .player canvas {
  display: block;
  position: absolute;
  width: 100%;
  height: 100%;
}
```
Thanks! It's a very nice extension.

-Godric
